### ISSUE TITLE
Hello, please making adaptation to iOS 13 when present modal view

### ISSUE THREAD

**Issue by lestadNew** [smartlook/ios-consent-sdk#8]
![Снимок экрана 2019-10-17 в 9 10 10 AM](https://user-images.githubusercontent.com/24388265/66981997-f87df400-f0bd-11e9-9c91-abace8885d83.png)

You can swipe this modal view and application is freeze

**Comment by pavel-kroh-smartlook** [comment]
Hi, I'm on it. The fix will be ready in few days.

**Comment by pavel-kroh-smartlook** [comment]
Hi again @lestadNew, I cannot reproduce the issue (in our Demo apps). Could you provide some more details or a minimal example?

**Comment by lestadNew** [comment]
@pavel-kroh-smartlook hi , In iOS 13, the default display of the modal window has changed, that is, you can close the controller when swiping. and when I do such a swipe, and not clicking on the confirm button, the application does not respond anymore to pressing, and if I press the button, then everything is fine. To avoid this, when displaying the controller, you need to add controller.modalPresentationStyle = .fullScreen and it will be displayed on the whole screen, as it was before iOS 13. That is, on the whole screen without the ability to swipe

**Comment by pavel-kroh-smartlook** [comment]
@lestadNew I see, it is apparently an issue on some devices only, I could not reproduce it on my older iPhone... but now I can see it in iPhone 11 simulator. Thanks for clarification, we will fix it soon.

**Comment by pavel-kroh-smartlook** [comment]
The issue was a bit more complicated (there already was the `.fullScreen` for iPhones, but it got ignored in some cases when the alert was shown from `AppDelegate`). Also, the issue was also present on iPad where we do not want the dialog fullscreen. 

Thus I used another flag on the alert controller that disables the gesture: `viewController.isModalInPresentation = true`

https://github.com/smartlook/ios-consent-sdk/blob/4141319908272c727a8d3913dc11b8b7ec8c468d/SmartlookConsentSDK/SmartlookConsentSDK/SmartlookConsentSDK.swift#L132

The fixed version 1.2.0 is released (and also tweaks the design to support Dark mode).
